# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f517e663be8a9defb223e356f65591bc7f338cf3a37a9801ef47a0469f78faa832f3d4f87dd03dade55b83dcf026f0b49abc1d301a11b86ad256a7c66d2e40a2

test:
  secret_key_base: 57c122b11d6596ef7938397eada99b48abd29817df7c639e7ae34b045666310c1310b14818482b4c311697a19406679a6c6023a6346ed1541ed7ebd0f84cf4a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
